# Generated by Django 2.2 on 2019-04-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwd_voter',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='pwd_voter',
            name='pick',
        ),
    ]
