# Generated by Django 2.2 on 2019-04-06 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0002_auto_20190407_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwd_voter',
            name='drop',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pwd_voter',
            name='pick',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
