# Generated by Django 2.2 on 2019-04-07 09:46

import constituency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0004_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to=constituency.models.user_path),
        ),
    ]
