# Generated by Django 2.2 on 2019-04-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0005_candidate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingstation',
            old_name='name',
            new_name='Pid',
        ),
    ]
