# Generated by Django 2.2 on 2019-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0006_auto_20190407_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='category',
            field=models.CharField(default='GEN', max_length=5),
        ),
    ]
