# Generated by Django 2.2 on 2019-04-08 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0007_voter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('stn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constituency.pollingStation')),
            ],
        ),
    ]
