# Generated by Django 2.2 on 2019-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituency', '0008_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwd_voter',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
